name: LED STUDIO
favicon: null
layout_spectrum: 0.954256885452196
typography_spectrum: 0.31109533086419106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6479519573040307
  lightness: 0.0628128363750875
  saturation: 0.819644026691094
  rhythmicContrast: 0.31957845599390566
purpose: []
