name: LED STUDIO
favicon: null
layout_spectrum: 0.954256885452196
typography_spectrum: 0.38455
title: LED STUDIO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#313131'
    - '#4b4b4b'
    - '#6e6e6e'
    - '#a2a2a2'
  brandStrength: 0.6479519573040307
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
